[IOFile]
# 输入文件路径：原始 Excel 数据文件，包含多个硬盘监控指标（支持绝对或相对路径）原始训练样本文件 模拟硬盘3项指标.xlsx 原始测试样本文件 test_samples.csv
input_file = data/模拟硬盘3项指标.xlsx

# 输出文件路径：提取并清洗后的 CSV 文件保存路径（将用于后续生成训练样本文件）基础训练样本文件 base_samples_2.csv  基础测试样本文件 test_samples_2.csv
output_file = sample/base_samples_2.csv 

[Features]
# 要提取的字段列表：从 Excel 中选取的列名，用逗号分隔
# 说明：
#   device_id        硬盘编号（唯一标识一块硬盘）
#   date             采集日期（建议为 yyyy-mm-dd 格式）
#   bad_sectors      当前坏道数量（SMART 指标）
#   remapped_sectors 已重映射扇区数（SMART 指标）
selected_fields = device_id, date, bad_sectors

# POH 处理策略：
# 0 → 不添加 POH
# 1 → 添加 POH
# 2 → 输入 CSV，仅添加 POH，不做抽取和清洗
poh = 1
